language: php

php:
  - 5.6

services:
  - redis-server

sudo: false

env:
  - REDIS_URI=localhost

before_script:
  - composer install --prefer-source --no-interaction --dev
  - composer dump-autoload

script: phpunit
